### ISSUE TITLE
Arch Linux: Expired signature & build error

### ISSUE THREAD

**Issue by leomeinel** [Cropi/usbguard-notifier#75] opened 2023-05-06 22:15 UTC
Hello,

A few days ago I have noticed that I can't manage to install this package with makepkg (Arch Linux install helper).
It seems like the signature for the newest release is expired and I am also getting some cxx build errors.

It doesn't seem like the main branch is getting the same build errors. But [0.1.0](https://github.com/Cropi/usbguard-notifier/releases/tag/usbguard-notifier-0.1.0) definetly does when using the above mentioned install method.

If you can't reproduce or think that this is invalid because I am not using the recommended install method, you are welcome to close this issue.

- [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=usbguard-notifier) from https://aur.archlinux.org/packages/usbguard-notifier
- [makepkg.log](https://github.com/leomeinel/arch-install/files/11413270/makepkg.log)
- [makepkg_--skippgpcheck.log](https://github.com/leomeinel/arch-install/files/11413271/makepkg_--skippgpcheck.log)
- [post.log](https://github.com/leomeinel/arch-install/files/11413272/post.log) from paru AUR helper

**Comment by leomeinel** [comment] 2023-05-06 23:07
https://wiki.archlinux.org/title/Laptop_Mode_Tools

**Comment by Daklon** [comment] 2023-06-29 18:52
I've reviewed this issue because i also faced it in arch, it seems like this problem was already fixed in the [latest commit](https://github.com/Cropi/usbguard-notifier/commit/f4586b732c8a7379aacbc9899173beeacfd54793) made in January.

The problem is that this fix is not in the latest tag, can you generate a new tag from the current main branch @Cropi?

**Comment by Strykar** [comment] 2024-03-06 03:08
@Cropi Any chance of a new release?
```
checking for notify... yes
checking for a2x... a2x
checking for catch.hpp... no
configure: error: in `/tmp/makepkg/usbguard-notifier/src/usbguard-notifier-0.1.0':
configure: error: catch.hpp not found or not
        usable. Re-run with --with-bundled-catch to use the bundled library.
See `config.log' for more details
```

**Comment by Cropi** [comment] 2024-03-19 09:56
Hello,
I created a new release with the fix mentioned above, see https://github.com/Cropi/usbguard-notifier/releases/tag/usbguard-notifier-0.1.1 .

**Closed by Cropi** 2024-03-19 09:56 UTC

**Comment by Cropi** [comment] 2024-03-19 09:58
> @Cropi Any chance of a new release?
> 
> ```
> checking for notify... yes
> checking for a2x... a2x
> checking for catch.hpp... no
> configure: error: in `/tmp/makepkg/usbguard-notifier/src/usbguard-notifier-0.1.0':
> configure: error: catch.hpp not found or not
>         usable. Re-run with --with-bundled-catch to use the bundled library.
> See `config.log' for more details
> ```

This is a separate issue. In order to build the project from sources, you need development files from catch. Either install them locally or use `--with-bundled-catch` when running `./configure`
